# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmput404_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='myEmail',
            field=models.CharField(default='not provided', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='myGithub',
            field=models.CharField(default='not provided', max_length=200),
            preserve_default=False,
        ),
    ]
