# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmput404_project', '0002_auto_20170228_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='myEmail',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='myGithub',
            new_name='Github',
        ),
        migrations.AddField(
            model_name='profile',
            name='Bio',
            field=models.CharField(default='not provided', max_length=200),
            preserve_default=False,
        ),
    ]
